<?php

namespace Database\Seeders;

use App\Models\Color;
use App\Models\User;
// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ColorSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        $colors = array(
                    array('color_code' => '#d96c6c'),
                    array('color_code' => '#735656'),
                    array('color_code' => '#a61600'),
                    array('color_code' => '#401610'),
                    array('color_code' => '#cca799'),
                    array('color_code' => '#ffb380'),
                    array('color_code' => '#592400'),
                    array('color_code' => '#cc6d00'),
                    array('color_code' => '#593c00'),
                    array('color_code' => '#e5ac39'),
                    array('color_code' => '#332b0d'),
                    array('color_code' => '#bfb68f'),
                    array('color_code' => '#ffee00'),
                    array('color_code' => '#739926'),
                    array('color_code' => '#d4ff80'),
                    array('color_code' => '#294010'),
                    array('color_code' => '#00cc1b'),
                    array('color_code' => '#60bf79'),
                    array('color_code' => '#4d6657'),
                    array('color_code' => '#208079'),
                    array('color_code' => '#40f2ff'),
                    array('color_code' => '#007a99'),
                    array('color_code' => '#003d4d'),
                    array('color_code' => '#7c9da6'),
                    array('color_code' => '#00aaff'),
                    array('color_code' => '#003059'),
                    array('color_code' => '#0044ff'),
                    array('color_code' => '#233f8c'),
                    array('color_code' => '#bfbfff'),
                    array('color_code' => '#25008c'),
                    array('color_code' => '#534d66'),
                    array('color_code' => '#9c66cc'),
                    array('color_code' => '#301040'),
                    array('color_code' => '#ad00d9'),
                    array('color_code' => '#cc99c2'),
                    array('color_code' => '#ff00aa'),
                    array('color_code' => '#8c235b'),
                    array('color_code' => '#e5005c'),
                    array('color_code' => '#40001a'),
                    array('color_code' => '#73001f'),
                    array('color_code' => '#ff0022'),
                    array('color_code' => '#ff0000'),
                    array('color_code' => '#995426'),
                    array('color_code' => '#fff780'),
                    array('color_code' => '#00e67a'),
                    array('color_code' => '#164359'),
                    array('color_code' => '#6d1d73'),
                    array('color_code' => '#cc99a0'),
                    array('color_code' => '#e50000'),
                    array('color_code' => '#ffa640'),
                    array('color_code' => '#364010'),
                    array('color_code' => '#008044'),
                    array('color_code' => '#8fafbf'),
                    array('color_code' => '#22134d'),
                    array('color_code' => '#f200c2'),
                    array('color_code' => '#403032'),
                    array('color_code' => '#d90000'),
                    array('color_code' => '#33210d'),
                    array('color_code' => '#697356'),
                    array('color_code' => '#00402b'),
                    array('color_code' => '#005299'),
                    array('color_code' => '#6600ff'),
                    array('color_code' => '#40002b'),
                    array('color_code' => '#731d1d'),
                    array('color_code' => '#7f6240'),
                    array('color_code' => '#529900'),
                    array('color_code' => '#40807b'),
                    array('color_code' => '#7391e6'),
                    array('color_code' => '#6c6080'),
                    array('color_code' => '#a6537f'),
                    array('color_code' => '#f29979'),
                    array('color_code' => '#ccbb99'),
                    array('color_code' => '#44ff00'),
                    array('color_code' => '#40f2ff'),
                    array('color_code' => '#3d55f2'),
                    array('color_code' => '#e1bfff'),
                    array('color_code' => '#f23d85'),
                    array('color_code' => '#ff6600'),
                    array('color_code' => '#7f7700'),
                    array('color_code' => '#bfffd0'),
                    array('color_code' => '#3db6f2'),
                    array('color_code' => '#00008c'),
                    array('color_code' => '#ca79f2'),
                    array('color_code' => '#f23d55'),
                    array('color_code' => '#bf8f8f'),
                    array('color_code' => '#ff2200'),
                    array('color_code' => '#e58273'),
                    array('color_code' => '#994526'),
                    array('color_code' => '#33170d'),
                    array('color_code' => '#f2853d'),
                    array('color_code' => '#f2ceb6'),
                    array('color_code' => '#99754d'),
                    array('color_code' => '#bf8000'),
                    array('color_code' => '#332200'),
                    array('color_code' => '#4c4700'),
                    array('color_code' => '#b2aa2d'),
                    array('color_code' => '#b6f23d'),
                    array('color_code' => '#4b731d'),
                    array('color_code' => '#9eb386'),
                    array('color_code' => '#104010'),
                    array('color_code' => '#00f241'),
                    array('color_code' => '#00b35f'),
                    array('color_code' => '#408073'),
                    array('color_code' => '#00ffee'),
                    array('color_code' => '#435958'),
                    array('color_code' => '#0d3033'),
                    array('color_code' => '#0099bf'),
                    array('color_code' => '#b6e6f2'),
                    array('color_code' => '#007ae6'),
                    array('color_code' => '#102940'),
                    array('color_code' => '#395073'),
                    array('color_code' => '#bfd0ff'),
                    array('color_code' => '#0018b3'),
                    array('color_code' => '#00004d'),
                    array('color_code' => '#6b4d99'),
                    array('color_code' => '#8100f2'),
                    array('color_code' => '#c480ff'),
                    array('color_code' => '#2b0d33'),
                    array('color_code' => '#bf00b3'),
                    array('color_code' => '#b386b0'),
                    array('color_code' => '#660052'),
                    array('color_code' => '#ff80d5'),
                    array('color_code' => '#403038'),
                    array('color_code' => '#cc3370'),
                    array('color_code' => '#f20041'),
                    array('color_code' => '#73001f'),
                    array('color_code' => '#330007')
         );

        DB::table((new Color)->getTable())->insert($colors);

    }
}
