<?php

namespace Database\Seeders;

use App\Models\Color;
// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ColorSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        $colors = [
            ['color_code' => '#d96c6c'],
            ['color_code' => '#735656'],
            ['color_code' => '#a61600'],
            ['color_code' => '#401610'],
            ['color_code' => '#cca799'],
            ['color_code' => '#ffb380'],
            ['color_code' => '#592400'],
            ['color_code' => '#cc6d00'],
            ['color_code' => '#593c00'],
            ['color_code' => '#e5ac39'],
            ['color_code' => '#332b0d'],
            ['color_code' => '#bfb68f'],
            ['color_code' => '#ffee00'],
            ['color_code' => '#739926'],
            ['color_code' => '#d4ff80'],
            ['color_code' => '#294010'],
            ['color_code' => '#00cc1b'],
            ['color_code' => '#60bf79'],
            ['color_code' => '#4d6657'],
            ['color_code' => '#208079'],
            ['color_code' => '#40f2ff'],
            ['color_code' => '#007a99'],
            ['color_code' => '#003d4d'],
            ['color_code' => '#7c9da6'],
            ['color_code' => '#00aaff'],
            ['color_code' => '#003059'],
            ['color_code' => '#0044ff'],
            ['color_code' => '#233f8c'],
            ['color_code' => '#bfbfff'],
            ['color_code' => '#25008c'],
            ['color_code' => '#534d66'],
            ['color_code' => '#9c66cc'],
            ['color_code' => '#301040'],
            ['color_code' => '#ad00d9'],
            ['color_code' => '#cc99c2'],
            ['color_code' => '#ff00aa'],
            ['color_code' => '#8c235b'],
            ['color_code' => '#e5005c'],
            ['color_code' => '#40001a'],
            ['color_code' => '#73001f'],
            ['color_code' => '#ff0022'],
            ['color_code' => '#ff0000'],
            ['color_code' => '#995426'],
            ['color_code' => '#fff780'],
            ['color_code' => '#00e67a'],
            ['color_code' => '#164359'],
            ['color_code' => '#6d1d73'],
            ['color_code' => '#cc99a0'],
            ['color_code' => '#e50000'],
            ['color_code' => '#ffa640'],
            ['color_code' => '#364010'],
            ['color_code' => '#008044'],
            ['color_code' => '#8fafbf'],
            ['color_code' => '#22134d'],
            ['color_code' => '#f200c2'],
            ['color_code' => '#403032'],
            ['color_code' => '#d90000'],
            ['color_code' => '#33210d'],
            ['color_code' => '#697356'],
            ['color_code' => '#00402b'],
            ['color_code' => '#005299'],
            ['color_code' => '#6600ff'],
            ['color_code' => '#40002b'],
            ['color_code' => '#731d1d'],
            ['color_code' => '#7f6240'],
            ['color_code' => '#529900'],
            ['color_code' => '#40807b'],
            ['color_code' => '#7391e6'],
            ['color_code' => '#6c6080'],
            ['color_code' => '#a6537f'],
            ['color_code' => '#f29979'],
            ['color_code' => '#ccbb99'],
            ['color_code' => '#44ff00'],
            ['color_code' => '#40f2ff'],
            ['color_code' => '#3d55f2'],
            ['color_code' => '#e1bfff'],
            ['color_code' => '#f23d85'],
            ['color_code' => '#ff6600'],
            ['color_code' => '#7f7700'],
            ['color_code' => '#bfffd0'],
            ['color_code' => '#3db6f2'],
            ['color_code' => '#00008c'],
            ['color_code' => '#ca79f2'],
            ['color_code' => '#f23d55'],
            ['color_code' => '#bf8f8f'],
            ['color_code' => '#ff2200'],
            ['color_code' => '#e58273'],
            ['color_code' => '#994526'],
            ['color_code' => '#33170d'],
            ['color_code' => '#f2853d'],
            ['color_code' => '#f2ceb6'],
            ['color_code' => '#99754d'],
            ['color_code' => '#bf8000'],
            ['color_code' => '#332200'],
            ['color_code' => '#4c4700'],
            ['color_code' => '#b2aa2d'],
            ['color_code' => '#b6f23d'],
            ['color_code' => '#4b731d'],
            ['color_code' => '#9eb386'],
            ['color_code' => '#104010'],
            ['color_code' => '#00f241'],
            ['color_code' => '#00b35f'],
            ['color_code' => '#408073'],
            ['color_code' => '#00ffee'],
            ['color_code' => '#435958'],
            ['color_code' => '#0d3033'],
            ['color_code' => '#0099bf'],
            ['color_code' => '#b6e6f2'],
            ['color_code' => '#007ae6'],
            ['color_code' => '#102940'],
            ['color_code' => '#395073'],
            ['color_code' => '#bfd0ff'],
            ['color_code' => '#0018b3'],
            ['color_code' => '#00004d'],
            ['color_code' => '#6b4d99'],
            ['color_code' => '#8100f2'],
            ['color_code' => '#c480ff'],
            ['color_code' => '#2b0d33'],
            ['color_code' => '#bf00b3'],
            ['color_code' => '#b386b0'],
            ['color_code' => '#660052'],
            ['color_code' => '#ff80d5'],
            ['color_code' => '#403038'],
            ['color_code' => '#cc3370'],
            ['color_code' => '#f20041'],
            ['color_code' => '#73001f'],
            ['color_code' => '#330007'],
        ];

        DB::table((new Color)->getTable())->insert($colors);

    }
}
